id: 2bbd9f2af0e14bd0ae76b08dbb558dbb
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_155-The_Question_of_the_Naga_King-v1
  language: en
  author: ''
  volume: {}
